import { expect, test } from "bun:test";
import { createDateAdapter, monthNames, monthYearOrder, weekdayNames } from "../../src/intl.js";

test("fr-BE adapter formats and parses the same civil date", () => {
  const adapter = createDateAdapter("fr-BE");
  expect(adapter.placeholder).toBe("DD/MM/YYYY");
  expect(adapter.format("2026-09-06")).toBe("06/09/2026");
  expect(adapter.parse("06/09/2026")).toBe("2026-09-06");
  expect(adapter.parse("2026-09-06")).toBe("2026-09-06");
});

test("en-US adapter uses locale field order", () => {
  const adapter = createDateAdapter("en-US");
  expect(adapter.parse(adapter.format("2026-09-06"))).toBe("2026-09-06");
});

test("locale names are generated by Intl", () => {
  expect(monthNames("fr-BE")).toHaveLength(12);
  expect(weekdayNames("fr-BE", 1)).toHaveLength(7);
});

test("monthYearOrder follows the Intl month/year order", () => {
  expect(monthYearOrder("en-US")).toEqual(["month", "year"]);
  expect(monthYearOrder("fr-BE")).toEqual(["month", "year"]);
  expect(monthYearOrder("ar")).toEqual(["month", "year"]);
  expect(monthYearOrder("ja")).toEqual(["year", "month"]);
  expect(monthYearOrder("zh-CN")).toEqual(["year", "month"]);
});

test("weekdayNames treats 7 as a Sunday alias without shifting 2+", () => {
  expect(weekdayNames("en", 7)).toEqual(weekdayNames("en", 0));
  expect(weekdayNames("en", 7)[0]).toBe("Sun");
  expect(weekdayNames("en", 2)[0]).toBe("Tue");
  expect(weekdayNames("en", 3)[0]).toBe("Wed");
});
