import { expect, test } from "bun:test";
import { createDateAdapter, monthNames, weekdayNames } from "../../src/intl.js";

test("fr-BE adapter formats and parses the same civil date", () => {
  const adapter = createDateAdapter("fr-BE");
  expect(adapter.placeholder).toBe("DD/MM/YYYY");
  expect(adapter.format("2026-09-06")).toBe("06/09/2026");
  expect(adapter.parse("06/09/2026")).toBe("2026-09-06");
  expect(adapter.parse("2026-09-06")).toBe("2026-09-06");
});

test("en-US adapter uses locale field order", () => {
  const adapter = createDateAdapter("en-US");
  expect(adapter.parse(adapter.format("2026-09-06"))).toBe("2026-09-06");
});

test("locale names are generated by Intl", () => {
  expect(monthNames("fr-BE")).toHaveLength(12);
  expect(weekdayNames("fr-BE", 1)).toHaveLength(7);
});
